from .aeropuerto import Aeropuerto
from .aeronave import Aeronave
from .vuelo import Vuelo
from .pasajero import Pasajero
from .reserva import Reserva
from .pais import Pais
from .ciudad import Ciudad
from .terminal import Terminal
from .puerta import Puerta
