# Generated by Django 6.0.5 on 2026-06-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_metodopago_pais_promocion_tarifa_tipoavion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('comida', 'Comida'), ('equipaje', 'Equipaje Extra'), ('asiento', 'Selección de Asiento'), ('wifi', 'WiFi'), ('seguro', 'Seguro de Viaje'), ('otro', 'Otro')], default='otro', max_length=20)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_checkin', models.DateTimeField(auto_now_add=True)),
                ('puerta', models.CharField(blank=True, max_length=10)),
                ('tarjeta_embarque', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('checkin', 'Check-in'), ('embarcado', 'Embarcado')], default='checkin', max_length=20)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='vuelos.reserva')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-hora_checkin'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='vuelos.reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('clase', models.CharField(choices=[('economica', 'Económica'), ('business', 'Business'), ('primera', 'Primera Clase')], default='economica', max_length=20)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=2)),
                ('disponible', models.BooleanField(default=True)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['vuelo', 'fila', 'columna'],
                'unique_together': {('vuelo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='vuelos.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.servicio')),
            ],
            options={
                'verbose_name': 'Reserva Servicio',
                'verbose_name_plural': 'Reserva Servicios',
                'unique_together': {('reserva', 'servicio')},
            },
        ),
    ]
